### ISSUE TITLE
Error encountered during depth order prediction training.

### ISSUE THREAD

**Issue by xingjianleng** [SHI-Labs/VCoder#5]
Dear Authors,

Thanks for the great work, and congratulations on getting accepted by CVPR!

I tried to train the VCoder model for depth order prediction by running `bash scripts/vcoder_ds_train.sh`. However, I encountered the following error.

```
Traceback (most recent call last):
  File "/g/data/kf09/xl9783/Code/VCoder/vcoder_llava/train/vcoder_ds_train_mem.py", line 15, in <module>
    vcoder_ds_train()
  File "/g/data/kf09/xl9783/Code/VCoder/vcoder_llava/train/vcoder_ds_train.py", line 1114, in vcoder_ds_train
    trainer.train()
  File "/home/135/xl9783/miniconda3/envs/vcoder/lib/python3.10/site-packages/transformers/trainer.py", line 1539, in train
    return inner_training_loop(
  File "/home/135/xl9783/miniconda3/envs/vcoder/lib/python3.10/site-packages/transformers/trainer.py", line 1624, in _inner_training_loop
    self.optimizer, self.lr_scheduler = deepspeed_init(self, num_training_steps=max_steps)
  File "/home/135/xl9783/miniconda3/envs/vcoder/lib/python3.10/site-packages/transformers/deepspeed.py", line 361, in deepspeed_init
    optimizer, lr_scheduler = deepspeed_optim_sched(
  File "/home/135/xl9783/miniconda3/envs/vcoder/lib/python3.10/site-packages/transformers/deepspeed.py", line 298, in deepspeed_optim_sched
    optimizer = trainer.create_optimizer()
  File "/g/data/kf09/xl9783/Code/VCoder/vcoder_llava/train/vcoder_ds_llava_trainer.py", line 163, in create_optimizer
    if self.args.depth_mm_projector_lr is not None:
AttributeError: 'TrainingArguments' object has no attribute 'depth_mm_projector_lr'
```
It seems that the `depth_mm_projector_lr` attribute is not provided in the shell script. May I ask for some suggestions on how to fix it?

Best,
Xingjian

**Comment by praeclarumjj3** [comment]
Hi @xingjianleng, Thanks for your interest and for bringing this to our attention! It seems that I forgot to remove a redundant part of the code while doing the cleanup. I have pushed a fix, and it should be working now. Feel free to ask any other questions.

**Comment by xingjianleng** [comment]
Hi @praeclarumjj3, thanks for fixing it! I'm closing this issue now.
